@node API
@chapter API

A setuptools file is provided to install @code{cic-notify} as a normal python package.

A single Python API method is provided so far:

@itemize @code
@item sms(recipient, content)
@end itemize

@code{recipient} is a string with phone number in @code{msisdn} format with a @code{+} prefix.

@code{content} is a UTF-8 string containing the message to be sent.
