@node Setup
@chapter Setup


@section Handlers

Notification tasks in this package are intended to be loaded dynamically, making no assumptions on which handlers that should be connected to the different tasks. The tasks provided are:

@itemize
@item 
@strong{notify.sms.log}: (none)
@item
@strong{notify.sms.db}: Postgresql, along with python packages alembic, SQLAlchemy and psycopg2.
@item
@strong{notify.sms.africastalking}: africastalking python package.
@end itemize

