\input texinfo
@settitle Grassroots Economics CIC ETH 0.4.1

@copying
Released 2020 under GPL3
@end copying

@titlepage
@title Community Inclusion Currency Network 
@author Louis Holbrook

@end titlepage

@c
@contents

@ifnottex
@node Top
@top Grassroots Economics CIC ETH

This document describes microservices that send transactions to and process events from an EVM blockchain.
@end ifnottex


@include overview.texi
@include setup.texi
@include run.texi
@include api.texi
