name: Docker Build Push

on:
  push:
    tags:
      - "v*"
  
jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1.14.1
      with: 
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker compose build push
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: |
        export TAG=$GITHUB_REF_NAME
        docker-compose -f docker-compose.build.yml build --progress plain
        docker-compose -f docker-compose.build.yml push
        export TAG=latest
        docker-compose -f docker-compose.build.yml build --progress plain
        docker-compose -f docker-compose.build.yml push
